## 没有异常的世界

一个例子 : 矩阵操作

```cpp
//结构体定义
typedef struct{
	float *data;
	size_t nrows;
	size_t ncols;
} matrix;
```

```cpp
//初始化和清理
enum matrix_err_code {
  MATRIX_SUCCESS,
  MATRIX_ERR_MEMORY_INSUFFICIENT,
  …
};

int matrix_alloc(matrix* ptr, size_t nrows, size_t ncols) {
  size_t size = nrows * ncols * sizeof(float);
  float* data = malloc(size);
  if (data == NULL) {
    return MATRIX_ERR_MEMORY_INSUFFICIENT;
  }
  ptr->data = data;
  ptr->nrows = nrows;
  ptr->ncols = ncols;
}

void matrix_dealloc(matrix* ptr) {
  if (ptr->data == NULL) {
    return;
  }
  free(ptr->data);
  ptr->data = NULL;
  ptr->nrows = 0;
  ptr->ncols = 0;
}
```

```cpp
//矩阵乘法
int matrix_multiply(matrix* result, const matrix* lhs, const matrix* rhs) {
  int errcode;
  if (lhs->ncols != rhs->nrows) {
    return MATRIX_ERR_MISMATCHED_MATRIX_SIZE;
    // 呃，得把这个错误码添到 enum matrix_err_code 里
  }
  errcode = matrix_alloc(result, lhs->nrows, rhs->ncols);
  if (errcode != MATRIX_SUCCESS) {
    return errcode;
  }
  // 进行矩阵乘法运算
  return MATRIX_SUCCESS;
}
```

```cpp
//调用
	
	matrix c;
  memset(&c, 0, sizeof(matrix)); // 不清零的话，错误处理和资源清理会更复杂
  errcode = matrix_multiply(c, a, b);
  if (errcode != MATRIX_SUCCESS) {
    goto error_exit;
  }
  // 使用乘法的结果做其他处理

error_exit:
  matrix_dealloc(&c);
  return errcode
```

以上矩阵从定义, 分配内存释放内存, 运算, 调试都有许多判断错误的代码, 分散在各处.

在C++中可以使用异常来处理这样的情况.

## C++中的异常

由于构造函数是无返回值的, 因此不能返回错误码. 实际上, 在构造函数里做清零工作, 而再使用一个 init 函数来做真正的构造操作.

```cpp
//类定义
class matrix {
  …
private:
  float* data_;
  size_t nrows_;
  size_t ncols_;
}
```

```cpp
//构造函数
matrix::matrix(size_t nrows,
               size_t ncols)
{
  data_  = new float[nrows * ncols];
  nrows_ = nrows;
  ncols_ = ncols;
}
```

```cpp
//析构函数
matrix::~matrix()
{
  delete[] data_;
}
```

```cpp
//矩阵乘法运算
class matrix {
  …
  friend matrix operator*(const matrix&, const matrix&);
};

matrix operator*(const matrix& lhs, const matrix& rhs) {
  if (lhs.ncols != rhs.nrows) {
    throw std::runtime_error("matrix sizes mismatch");
  }
  matrix result(lhs.nrows, rhs.ncols);
  // 进行矩阵乘法运算
  return result;
}
```

```cpp
//调用
matrix c = a * b;
```

其中只有一个 `throw` , 异常安全并不意味着需要写显式的 `try` 和 `catch`, 异常安全的代码可以没有任何 `try` 和 `catch`.

## 异常安全

异常安全 : 当异常发生时, 既不会发生内存泄漏, 系统也不会处于一个不一致的状态.

这段代码中, 可能出现异常的地方:

- 内存分配. 如果 new 出错, 按照C++规则, 会得到异常 bad_alloc, 对象会构造失败. 这种情况下, 所有的栈上的对象全部被析构, 资源全部被自动清理.
- 长款不合适做乘法. 会使得对象 c 不会被构造.
- 乘法函数里内存分配失败. result对象根本没有被构造出来, 也就没有 c 对象.
- a, b是本地变量, 如果乘法失败. 析构函数会自动释放空间, 我们同样不会有任何资源泄漏.

> 出于对性能的追求, 异常是会被禁用的. 在游戏项目中或者军事项目中.

现有主流C++编译器, 在异常关闭和异常开启的情况下能够产生差不多的代码, 但是代价是有10%到20%的二进制文件大小的增加.

C++17以来, C++完全禁止了动态异常规约, 不能再在函数声明里写你可能会抛出某某异常, 现在能写的是 noexcept, noexcept(true), throw().

作者的建议:

1. 写异常安全的代码, 尤其是在模板里. 可能的话, 提供强异常安全保证.
2. 如果你的代码可能抛出异常的话，在文档里明确声明可能发生的异常类型和发生条件。确保使用你的代码的人，能在不检查你的实现的情况，了解需要准备处理哪些异常。
3. 对于肯定不会抛出异常的代码，将其标为 noexcept。注意类的特殊成员（构造函数、析构函数、赋值函数等）会自动成为 noexcept，如果它们调用的代码都是 noexcept 的话。所以，像 swap 这样的成员函数应当尽可能标成 noexcept。

## 使用异常的理由

标准库的错误处理方式就是异常. 其中不尽包括运行时错误, 还包括一些逻辑错误.

比如说, 容器在使用 [] 运算符时, C++标准容器也提供了 at 的成员函数, 能够在下标不存在的时候抛出异常.

```cpp
vector<int> v{1,2,3};

v[0]    //1
v.at(0) //1
v[3]    //-1342175236
v.at(3) //异常 : _M_range_check: __n (which is 3) >= this->size() (which is 3)
```

C++的标准容器在大部分情况下提供强异常安全, 即发生异常, 现场会恢复到调用函数之前的状态, 容器内的状态不会发生改变, 没有资源泄漏.

前文提到的, vector中元素如果需要 move , 一定得有一个 noexcept 修饰的移动构造函数, 否则如果在 move 过程中出现了异常, 被移动的元素已经被破坏, 处于只有析构的状态, 异常安全性就不能得到保证.

需要标准 noexcept 的地方:

1. 构造, 析构, 赋值缺省 noexcept
2. 移动构造函数, 移动赋值函数和 swap 函数需要 noexcept
3. 其他很小的返回引用和指针的函数
